import mongoose,{Schema} from 'mongoose'
const userSchema=new Schema({
    user_id:{
        type:Schema.Types.ObjectId,
        ref:"Leaderboard"
    },
    username:{
        type:String,
        required:true,
        unique:true,
        lowercase:true,
        trim:true,
        index:true
    },
    email:{
        type:String,
        required:true,
        unique:true,
        lowercase:true,
        trim:true
    },
    fullname:{
        type:String,
        required:true,
        trim:true,
        index:true
    },
    password:{
        type:String,//encrypted
        required:[true,'password is required']
    },
    quizid:{
        type:Schema.Types.ObjectId,
        ref:"Quiz"
    },
    numberofquizsdone:{
        type:Schema.Types.ObjectId,
        ref:"quizquestion"
    },
    profilepic:{
        type:String,
        required:true
    },
    role:{
        type:String,
        enum:['learner','admin'],
        default:'learner'
    },
    status:{
        type:String,
        enum:['active','inactive'],
        default:'active'
    },
    lastlogin:{
        type:Date
    },
    refreshToken:{
        type:String
    }

},{timestamps:true})
export const User=mongoose.model("User",userSchema)